# Generated by Django 4.1.13 on 2024-02-05 19:38

import course.model_classes.attendee
import course.model_classes.bookinginvoice
import course.model_classes.certificate
import course.model_classes.course
import course.model_classes.enquiry
import course.model_classes.hotel
import course.model_classes.venue
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', djongo.models.fields.EmbeddedField(model_container=course.model_classes.venue.Venue)),
                ('hotel', djongo.models.fields.EmbeddedField(model_container=course.model_classes.hotel.Hotel)),
                ('bookinginvoices', djongo.models.fields.ArrayField(model_container=course.model_classes.bookinginvoice.Bookinginvoice)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('building_number_and_thoroughfare_name', models.CharField(blank=True, max_length=255, null=True)),
                ('locality_name', models.CharField(blank=True, max_length=255, null=True)),
                ('town_name', models.CharField(blank=True, max_length=255, null=True)),
                ('administrative_area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('county_name', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'db_table': 'address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookinginvoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instruction_email_address', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_result_email_address', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instruction_sent_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Attendees',
                'db_table': 'attendee',
            },
        ),
        migrations.CreateModel(
            name='Bookinginvoice',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', djongo.models.fields.ArrayField(model_container=course.model_classes.attendee.Attendee)),
                ('party_id', models.CharField(blank=True, max_length=255, null=True)),
                ('address_id', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_method', models.IntegerField(blank=True, null=True)),
                ('po_or_ref_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bookinginvoices',
                'db_table': 'bookinginvoice',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_code', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('certification_body', models.CharField(blank=True, max_length=255, null=True)),
                ('link_to_syllabus', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Certificates',
                'db_table': 'certificate',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookinginvoices', djongo.models.fields.ArrayField(model_container=course.model_classes.bookinginvoice.Bookinginvoice)),
                ('attendees', djongo.models.fields.ArrayField(model_container=course.model_classes.attendee.Attendee)),
                ('venue_id', models.CharField(blank=True, max_length=255, null=True)),
                ('course_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('attendee_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiries', djongo.models.fields.ArrayField(model_container=course.model_classes.enquiry.Enquiry)),
                ('courses', djongo.models.fields.ArrayField(model_container=course.model_classes.course.Course)),
                ('certificates', djongo.models.fields.ArrayField(model_container=course.model_classes.certificate.Certificate)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_mode', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Course Types',
                'db_table': 'course_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('party_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'db_table': 'enquiry',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue_id', models.CharField(blank=True, max_length=255, null=True)),
                ('address_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_website', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookinginvoices', djongo.models.fields.ArrayField(model_container=course.model_classes.bookinginvoice.Bookinginvoice)),
                ('enquiries', djongo.models.fields.ArrayField(model_container=course.model_classes.enquiry.Enquiry)),
                ('email_address', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved_supplier_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'db_table': 'party',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', djongo.models.fields.ArrayField(model_container=course.model_classes.course.Course)),
                ('hotels', djongo.models.fields.ArrayField(model_container=course.model_classes.hotel.Hotel)),
                ('address_id', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_contact_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Venues',
                'db_table': 'venue',
            },
        ),
    ]
