from .address_admin import AddressAdmin
from .attendee_admin import AttendeeAdmin
from .bookinginvoice_admin import BookinginvoiceAdmin
from .certificate_admin import CertificateAdmin
from .contact_admin import ContactAdmin
from .course_type_admin import CourseTypeAdmin
from .course_admin import CourseAdmin
from .enquiry_admin import EnquiryAdmin
from .hotel_admin import HotelAdmin
from .company_admin import CompanyAdmin
from .venue_admin import VenueAdmin